//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGPHOOKAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostOffice
    {
        public string PostOfficeID { get; set; }
        public string PostOfficeName { get; set; }
        public string Address { get; set; }
        public string ZoneID { get; set; }
        public string ProvinceID { get; set; }
        public string Phone { get; set; }
        public string DistrictID { get; set; }
    }
}
