//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGPHOOKAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerPost
    {
        public string CustomerID { get; set; }
        public string PostID { get; set; }
        public string PMSCusID { get; set; }
        public string GroupID { get; set; }
        public string ZoneID { get; set; }
    }
}
