//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGPHOOKAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerAddress
    {
        public string Id { get; set; }
        public string CusName { get; set; }
        public string CusAddress { get; set; }
        public string CusProvinceId { get; set; }
        public string CusPhone { get; set; }
    }
}
