//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGPHOOKAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int Id { get; set; }
        public string TypeCode { get; set; }
        public string DeviceCode { get; set; }
        public string CGNumber { get; set; }
        public string FTPServer { get; set; }
        public string FolderPath { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
