//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGPHOOKAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FPTVendorCode
    {
        public string Id { get; set; }
        public string VendorName { get; set; }
        public string OrgCode { get; set; }
        public string ProvinceCode { get; set; }
        public string SGPPostOffice { get; set; }
    }
}
