//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGPHOOKAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerAccount
    {
        public int Id { get; set; }
        public string PartnerName { get; set; }
        public string PartnerCode { get; set; }
        public string Token { get; set; }
        public string APIUrl { get; set; }
    }
}
