//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGPHOOKAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SAIGONPOSTDBEntities : DbContext
    {
        public SAIGONPOSTDBEntities()
            : base("name=SAIGONPOSTDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<CustomerAddress> CustomerAddresses { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<MailerInfo> MailerInfoes { get; set; }
        public virtual DbSet<OrderItem> OrderItems { get; set; }
        public virtual DbSet<PartnerAccount> PartnerAccounts { get; set; }
        public virtual DbSet<PostOffice> PostOffices { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<TrackingOrder> TrackingOrders { get; set; }
        public virtual DbSet<FPTVendorCode> FPTVendorCodes { get; set; }
        public virtual DbSet<CustomerPost> CustomerPosts { get; set; }
    
        public virtual ObjectResult<get_mailer_fpt_Result> get_mailer_fpt(string orderid)
        {
            var orderidParameter = orderid != null ?
                new ObjectParameter("orderid", orderid) :
                new ObjectParameter("orderid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_mailer_fpt_Result>("get_mailer_fpt", orderidParameter);
        }
    
        public virtual ObjectResult<get_mailers_Result> get_mailers(string fdate, string tdate, string mailerid, string cusid, string postId)
        {
            var fdateParameter = fdate != null ?
                new ObjectParameter("fdate", fdate) :
                new ObjectParameter("fdate", typeof(string));
    
            var tdateParameter = tdate != null ?
                new ObjectParameter("tdate", tdate) :
                new ObjectParameter("tdate", typeof(string));
    
            var maileridParameter = mailerid != null ?
                new ObjectParameter("mailerid", mailerid) :
                new ObjectParameter("mailerid", typeof(string));
    
            var cusidParameter = cusid != null ?
                new ObjectParameter("cusid", cusid) :
                new ObjectParameter("cusid", typeof(string));
    
            var postIdParameter = postId != null ?
                new ObjectParameter("postId", postId) :
                new ObjectParameter("postId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_mailers_Result>("get_mailers", fdateParameter, tdateParameter, maileridParameter, cusidParameter, postIdParameter);
        }
    }
}
